/******************************************************/
/* THIS FILE WAS AUTOMATICALLY GENERATED BY KEY2CODE. */
/* PLEASE DO NOT MODIFY.                              */
/******************************************************/

#include "HUKFactor.h"
static const uint32_t HUKFactor_cForm0[] = {
 3856303144u,
 3732376365u,
 964075786u,
 3732376365u,
 3330891510u,
 1125181862u,
 4111418174u,
 3330891510u};

static const uint32_t HUKFactor_cForm1[] = {
 1161166848u,
 2261516288u,
 3158475389u,
 2715729601u,
 23894822u,
 924188672u,
 4178463873u,
 4123546441u,
 3150184448u,
 1046251916u,
 2510320317u,
 3771841338u,
 892323489u,
 1638490830u,
 2421125062u,
 3747684468u,
 4294967295u,
 401460854u,
};

static const uint32_t HUKFactor_cForm3[] = {
 1009404553u,
 3285562743u,
 494927872u,
 813694976u,
 2791309312u,
 3788835928u,
 604476792u,
 3737102599u,
 1845245252u,
 278932348u,
 2108912757u,
 2348127185u,
 1353575069u,
 3156021559u,
 4260295012u,
 235503460u,
 898243140u,
 2982080556u,
 4098960956u,
 2358902784u,
 736095521u,
 2860046130u,
};

const uint32_t HUKFactor_form3_consts_0[] = {
  4287830818u, 
  1895013082u, 
};

const uint32_t HUKFactor_form0_consts_1[] = {
  1831727460u, 
  2526049504u, 
  1868950676u, 
};

const uint32_t HUKFactor_form3_consts_2[] = {
  2806952933u, 
  88765681u, 
};

const uint32_t HUKFactor_form0_consts_3[] = {
  2051424027u, 
  768476968u, 
  786738751u, 
};

const uint32_t HUKFactor_form0_consts_4[] = {
  2918413285u, 
  2422497496u, 
  933906625u, 
};

const uint32_t HUKFactor_form0_consts_5[] = {
  1963503330u, 
  1471842544u, 
  3205309626u, 
};

const uint32_t HUKFactor_form1_consts_6[] = {
  1304428544u, 
  100663296u, 
  3900702720u, 
  2344615936u, 
  3009372496u, 
  631913884u, 
  3031139528u, 
};

const uint32_t HUKFactor_form3_consts_7[] = {
  202419438u, 
  3357691638u, 
};

const uint32_t HUKFactor_form1_consts_8[] = {
  3555721216u, 
  2187329536u, 
  1897922560u, 
  1198522368u, 
  3741985460u, 
  4090244591u, 
  409445410u, 
};

const uint32_t HUKFactor_form0_consts_9[] = {
  1767224820u, 
  3042070624u, 
  604107236u, 
};

const uint32_t HUKFactor_form0_consts_10[] = {
  2239358976u, 
  3559964672u, 
  3109668864u, 
};

const uint32_t HUKFactor_form3_consts_11[] = {
  1226454194u, 
  735035434u, 
};


int32_t HUKFactor0(uint8_t (*bp)[48],int param0,int param1,int param2,int param3,int param4) 
 { 
 int32_t x = -1;
 int32_t i,y,z,z0,z1,z2;
\
   \
    y = (HUKFactor_cForm3[0]*param3|HUKFactor_form3_consts_0[0])+     \
        ((HUKFactor_cForm3[1]*param3-1)|HUKFactor_form3_consts_0[0]); \
    z2 = HUKFactor_cForm3[2]*param4*param4+HUKFactor_cForm3[3]*param4*param3     \
         +HUKFactor_cForm3[4]*param3*param3+HUKFactor_cForm3[5]*param4     \
         -((HUKFactor_cForm3[6]*param3-1)|HUKFactor_cForm3[7])    \
         +((HUKFactor_cForm3[8]*param3)^HUKFactor_cForm3[9])+HUKFactor_cForm3[10]; \
    z0 = HUKFactor_cForm3[11]*param4 + 4770*((HUKFactor_cForm3[12]*param4*param4+892)|HUKFactor_cForm3[13]*param4); \
    z1 = z0&0x1; \
    for(i=1; i<=31; i++){   \
        z1 = z1^((z0 + HUKFactor_cForm3[14]*z1 +  \
        4770+4770*((-127237*z1*z1-893)|7269*z1) )&(0x1<<((uint32_t)i))); \
    } \
    x = HUKFactor_cForm3[15]*y+ HUKFactor_cForm3[16]*param4 + HUKFactor_cForm3[17]*z1+ HUKFactor_cForm3[18]*param3 \
        +HUKFactor_cForm3[19]*z2*z2 +HUKFactor_cForm3[20]*z2 + HUKFactor_form3_consts_0[1] + HUKFactor_cForm3[21]; \
;  \
   \
  (*bp)[0] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[1] = (uint8_t) (((uint32_t) x) >> 16);
  (*bp)[2] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[3] = (uint8_t) x;

  x = HUKFactor_cForm0[0]*((HUKFactor_form0_consts_1[0]^((param4*HUKFactor_cForm0[1])>>0x2))) \
        +HUKFactor_cForm0[2]*((param4*HUKFactor_cForm0[3])&0x3) \
        +HUKFactor_cForm0[4]*((HUKFactor_form0_consts_1[1]-0x1)|(HUKFactor_cForm0[5]*param4-0x1)) \
        +HUKFactor_form0_consts_1[2]+HUKFactor_cForm0[6]*param4 \
        +HUKFactor_cForm0[7];   (*bp)[4] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[5] = (uint8_t) (((uint32_t) x) >> 16);
  (*bp)[6] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[7] = (uint8_t) x;

\
   \
    y = (HUKFactor_cForm3[0]*(*bp)[35]|HUKFactor_form3_consts_2[0])+     \
        ((HUKFactor_cForm3[1]*(*bp)[35]-1)|HUKFactor_form3_consts_2[0]); \
    z2 = HUKFactor_cForm3[2]*param4*param4+HUKFactor_cForm3[3]*param4*(*bp)[35]     \
         +HUKFactor_cForm3[4]*(*bp)[35]*(*bp)[35]+HUKFactor_cForm3[5]*param4     \
         -((HUKFactor_cForm3[6]*(*bp)[35]-1)|HUKFactor_cForm3[7])    \
         +((HUKFactor_cForm3[8]*(*bp)[35])^HUKFactor_cForm3[9])+HUKFactor_cForm3[10]; \
    z0 = HUKFactor_cForm3[11]*param4 + 4770*((HUKFactor_cForm3[12]*param4*param4+892)|HUKFactor_cForm3[13]*param4); \
    z1 = z0&0x1; \
    for(i=1; i<=31; i++){   \
        z1 = z1^((z0 + HUKFactor_cForm3[14]*z1 +  \
        4770+4770*((-127237*z1*z1-893)|7269*z1) )&(0x1<<((uint32_t)i))); \
    } \
    x = HUKFactor_cForm3[15]*y+ HUKFactor_cForm3[16]*param4 + HUKFactor_cForm3[17]*z1+ HUKFactor_cForm3[18]*(*bp)[35] \
        +HUKFactor_cForm3[19]*z2*z2 +HUKFactor_cForm3[20]*z2 + HUKFactor_form3_consts_2[1] + HUKFactor_cForm3[21]; \
;  \
   \
  (*bp)[8] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[9] = (uint8_t) (((uint32_t) x) >> 16);
 if(((*bp)[8] >= (*bp)[9])) {
  (*bp)[11] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[10] = (uint8_t) x;
 }
 else {
  (*bp)[10] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[11] = (uint8_t) x;
 }

 return 0; 
 }


int32_t HUKFactor1(uint8_t (*bp)[48],int param0,int param1,int param2,int param3,int param4) 
 { 
 int32_t x = -1;
 int32_t i,y,z,z0,z1,z2;
  x = HUKFactor_cForm0[0]*((HUKFactor_form0_consts_3[0]^((HUKFactor_cForm1[11]*HUKFactor_cForm0[1])>>0x2))) \
        +HUKFactor_cForm0[2]*((HUKFactor_cForm1[11]*HUKFactor_cForm0[3])&0x3) \
        +HUKFactor_cForm0[4]*((HUKFactor_form0_consts_3[1]-0x1)|(HUKFactor_cForm0[5]*HUKFactor_cForm1[11]-0x1)) \
        +HUKFactor_form0_consts_3[2]+HUKFactor_cForm0[6]*HUKFactor_cForm1[11] \
        +HUKFactor_cForm0[7];   (*bp)[12] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[13] = (uint8_t) (((uint32_t) x) >> 16);
  (*bp)[14] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[15] = (uint8_t) x;

  x = HUKFactor_cForm0[0]*((HUKFactor_form0_consts_4[0]^((param2*HUKFactor_cForm0[1])>>0x2))) \
        +HUKFactor_cForm0[2]*((param2*HUKFactor_cForm0[3])&0x3) \
        +HUKFactor_cForm0[4]*((HUKFactor_form0_consts_4[1]-0x1)|(HUKFactor_cForm0[5]*param2-0x1)) \
        +HUKFactor_form0_consts_4[2]+HUKFactor_cForm0[6]*param2 \
        +HUKFactor_cForm0[7];   (*bp)[16] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[17] = (uint8_t) (((uint32_t) x) >> 16);
 if(((*bp)[16] >= (*bp)[17])) {
  (*bp)[19] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[18] = (uint8_t) x;
 }
 else {
  (*bp)[18] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[19] = (uint8_t) x;
 }

  x = HUKFactor_cForm0[0]*((HUKFactor_form0_consts_5[0]^((param1*HUKFactor_cForm0[1])>>0x2))) \
        +HUKFactor_cForm0[2]*((param1*HUKFactor_cForm0[3])&0x3) \
        +HUKFactor_cForm0[4]*((HUKFactor_form0_consts_5[1]-0x1)|(HUKFactor_cForm0[5]*param1-0x1)) \
        +HUKFactor_form0_consts_5[2]+HUKFactor_cForm0[6]*param1 \
        +HUKFactor_cForm0[7];   (*bp)[20] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[21] = (uint8_t) (((uint32_t) x) >> 16);
 if(((*bp)[20] > (*bp)[21])) {
  (*bp)[22] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[23] = (uint8_t) x;
 }
 else {
  (*bp)[23] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[22] = (uint8_t) x;
 }

   z = HUKFactor_cForm1[0]*param3*param3+HUKFactor_form1_consts_6[0]*param3 \
        +HUKFactor_cForm1[1]*param3*HUKFactor_cForm1[12]+HUKFactor_form1_consts_6[1]  \
        -((HUKFactor_form1_consts_6[2]*HUKFactor_cForm1[12]-1)|HUKFactor_cForm1[2])  \
        + ((HUKFactor_form1_consts_6[3]*HUKFactor_cForm1[12])^HUKFactor_cForm1[3])  \
        + HUKFactor_cForm1[4]  \
        +HUKFactor_cForm1[5]*HUKFactor_cForm1[12] *HUKFactor_cForm1[12] \
        +HUKFactor_cForm1[6]*param3+HUKFactor_form1_consts_6[4] \
        +HUKFactor_cForm1[7]*HUKFactor_cForm1[12]; \
    y = HUKFactor_cForm1[8]*z*z-((HUKFactor_cForm1[9]*z-1)|(HUKFactor_cForm1[10])) \
         +((HUKFactor_cForm1[11]*z)^HUKFactor_cForm1[12])+HUKFactor_cForm1[13]; \
    x = ((HUKFactor_cForm1[14]*param3)^HUKFactor_form1_consts_6[5]) \
        -((HUKFactor_cForm1[15]*param3+HUKFactor_cForm1[16])|(HUKFactor_form1_consts_6[6]+HUKFactor_cForm1[16]))-1 \
        + HUKFactor_cForm1[17]*HUKFactor_cForm1[12] + y; \
  (*bp)[24] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[25] = (uint8_t) (((uint32_t) x) >> 16);
  (*bp)[26] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[27] = (uint8_t) x;

\
   \
    y = (HUKFactor_cForm3[0]*HUKFactor_cForm1[13]|HUKFactor_form3_consts_7[0])+     \
        ((HUKFactor_cForm3[1]*HUKFactor_cForm1[13]-1)|HUKFactor_form3_consts_7[0]); \
    z2 = HUKFactor_cForm3[2]*(*bp)[27]*(*bp)[27]+HUKFactor_cForm3[3]*(*bp)[27]*HUKFactor_cForm1[13]     \
         +HUKFactor_cForm3[4]*HUKFactor_cForm1[13]*HUKFactor_cForm1[13]+HUKFactor_cForm3[5]*(*bp)[27]     \
         -((HUKFactor_cForm3[6]*HUKFactor_cForm1[13]-1)|HUKFactor_cForm3[7])    \
         +((HUKFactor_cForm3[8]*HUKFactor_cForm1[13])^HUKFactor_cForm3[9])+HUKFactor_cForm3[10]; \
    z0 = HUKFactor_cForm3[11]*(*bp)[27] + 4770*((HUKFactor_cForm3[12]*(*bp)[27]*(*bp)[27]+892)|HUKFactor_cForm3[13]*(*bp)[27]); \
    z1 = z0&0x1; \
    for(i=1; i<=31; i++){   \
        z1 = z1^((z0 + HUKFactor_cForm3[14]*z1 +  \
        4770+4770*((-127237*z1*z1-893)|7269*z1) )&(0x1<<((uint32_t)i))); \
    } \
    x = HUKFactor_cForm3[15]*y+ HUKFactor_cForm3[16]*(*bp)[27] + HUKFactor_cForm3[17]*z1+ HUKFactor_cForm3[18]*HUKFactor_cForm1[13] \
        +HUKFactor_cForm3[19]*z2*z2 +HUKFactor_cForm3[20]*z2 + HUKFactor_form3_consts_7[1] + HUKFactor_cForm3[21]; \
;  \
   \
  (*bp)[28] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[29] = (uint8_t) (((uint32_t) x) >> 16);
 if(((*bp)[28] <= (*bp)[29])) {
  (*bp)[31] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[30] = (uint8_t) x;
 }
 else {
  (*bp)[30] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[31] = (uint8_t) x;
 }

   z = HUKFactor_cForm1[0]*param0*param0+HUKFactor_form1_consts_8[0]*param0 \
        +HUKFactor_cForm1[1]*param0*param2+HUKFactor_form1_consts_8[1]  \
        -((HUKFactor_form1_consts_8[2]*param2-1)|HUKFactor_cForm1[2])  \
        + ((HUKFactor_form1_consts_8[3]*param2)^HUKFactor_cForm1[3])  \
        + HUKFactor_cForm1[4]  \
        +HUKFactor_cForm1[5]*param2 *param2 \
        +HUKFactor_cForm1[6]*param0+HUKFactor_form1_consts_8[4] \
        +HUKFactor_cForm1[7]*param2; \
    y = HUKFactor_cForm1[8]*z*z-((HUKFactor_cForm1[9]*z-1)|(HUKFactor_cForm1[10])) \
         +((HUKFactor_cForm1[11]*z)^HUKFactor_cForm1[12])+HUKFactor_cForm1[13]; \
    x = ((HUKFactor_cForm1[14]*param0)^HUKFactor_form1_consts_8[5]) \
        -((HUKFactor_cForm1[15]*param0+HUKFactor_cForm1[16])|(HUKFactor_form1_consts_8[6]+HUKFactor_cForm1[16]))-1 \
        + HUKFactor_cForm1[17]*param2 + y; \
  (*bp)[32] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[33] = (uint8_t) (((uint32_t) x) >> 16);
  (*bp)[34] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[35] = (uint8_t) x;

  x = HUKFactor_cForm0[0]*((HUKFactor_form0_consts_9[0]^((HUKFactor_cForm3[10]*HUKFactor_cForm0[1])>>0x2))) \
        +HUKFactor_cForm0[2]*((HUKFactor_cForm3[10]*HUKFactor_cForm0[3])&0x3) \
        +HUKFactor_cForm0[4]*((HUKFactor_form0_consts_9[1]-0x1)|(HUKFactor_cForm0[5]*HUKFactor_cForm3[10]-0x1)) \
        +HUKFactor_form0_consts_9[2]+HUKFactor_cForm0[6]*HUKFactor_cForm3[10] \
        +HUKFactor_cForm0[7];   (*bp)[36] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[37] = (uint8_t) (((uint32_t) x) >> 16);
  (*bp)[38] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[39] = (uint8_t) x;

  x = HUKFactor_cForm0[0]*((HUKFactor_form0_consts_10[0]^((HUKFactor_cForm0[2]*HUKFactor_cForm0[1])>>0x2))) \
        +HUKFactor_cForm0[2]*((HUKFactor_cForm0[2]*HUKFactor_cForm0[3])&0x3) \
        +HUKFactor_cForm0[4]*((HUKFactor_form0_consts_10[1]-0x1)|(HUKFactor_cForm0[5]*HUKFactor_cForm0[2]-0x1)) \
        +HUKFactor_form0_consts_10[2]+HUKFactor_cForm0[6]*HUKFactor_cForm0[2] \
        +HUKFactor_cForm0[7];   (*bp)[40] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[41] = (uint8_t) (((uint32_t) x) >> 16);
 if(((*bp)[40] >= (*bp)[41])) {
  (*bp)[43] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[42] = (uint8_t) x;
 }
 else {
  (*bp)[42] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[43] = (uint8_t) x;
 }

\
   \
    y = (HUKFactor_cForm3[0]*param2|HUKFactor_form3_consts_11[0])+     \
        ((HUKFactor_cForm3[1]*param2-1)|HUKFactor_form3_consts_11[0]); \
    z2 = HUKFactor_cForm3[2]*param2*param2+HUKFactor_cForm3[3]*param2*param2     \
         +HUKFactor_cForm3[4]*param2*param2+HUKFactor_cForm3[5]*param2     \
         -((HUKFactor_cForm3[6]*param2-1)|HUKFactor_cForm3[7])    \
         +((HUKFactor_cForm3[8]*param2)^HUKFactor_cForm3[9])+HUKFactor_cForm3[10]; \
    z0 = HUKFactor_cForm3[11]*param2 + 4770*((HUKFactor_cForm3[12]*param2*param2+892)|HUKFactor_cForm3[13]*param2); \
    z1 = z0&0x1; \
    for(i=1; i<=31; i++){   \
        z1 = z1^((z0 + HUKFactor_cForm3[14]*z1 +  \
        4770+4770*((-127237*z1*z1-893)|7269*z1) )&(0x1<<((uint32_t)i))); \
    } \
    x = HUKFactor_cForm3[15]*y+ HUKFactor_cForm3[16]*param2 + HUKFactor_cForm3[17]*z1+ HUKFactor_cForm3[18]*param2 \
        +HUKFactor_cForm3[19]*z2*z2 +HUKFactor_cForm3[20]*z2 + HUKFactor_form3_consts_11[1] + HUKFactor_cForm3[21]; \
;  \
   \
  (*bp)[44] = (uint8_t) (((uint32_t) x) >> 24);
  (*bp)[45] = (uint8_t) (((uint32_t) x) >> 16);
 if(((*bp)[44] >= (*bp)[45])) {
  (*bp)[47] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[46] = (uint8_t) x;
 }
 else {
  (*bp)[46] = (uint8_t) (((uint32_t) x) >> 8);
  (*bp)[47] = (uint8_t) x;
 }

 return 0; 
 }

