/******************************************************/
/* THIS FILE WAS AUTOMATICALLY GENERATED BY KEY2CODE. */
/* PLEASE DO NOT MODIFY.                              */
/******************************************************/

#include <stdint.h>
typedef int32_t (*HUKFactor_type)( uint8_t (*)[48],  int32_t,  int32_t,  int32_t,  int32_t,  int32_t);


int32_t HUKFactor0(uint8_t (*bp)[48],int param0,int param1,int param2,int param3,int param4)
;

int32_t HUKFactor1(uint8_t (*bp)[48],int param0,int param1,int param2,int param3,int param4)
;
